### ISSUE TITLE
Fix regex to add missing type to rules

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/flasgger#10]
Currently rules only work if type is defined

bad
```
@route('/<param>/<another>')
```

good
```
@route('/<string:param>/<string:another>')
```

But we should accept the first, so regex have to be fixed.

**Comment by rochacbruno** [comment]
The example: https://regex101.com/r/iL3jK2/3

**Comment by rochacbruno** [comment]
![download](https://cloud.githubusercontent.com/assets/458654/12306696/30280f5c-ba22-11e5-880b-fa4cb7464832.png)

**Comment by rochacbruno** [comment]
Codeline: https://github.com/rochacbruno/flasgger/blob/master/flasgger/base.py#L288

**Comment by jfunez** [comment]
tem que dar 6 matches, certo?
pode ser assim?:
``(<(.*?\:\>)?(.*?)>)``


![screenshot 2016-01-13 18 28 07](https://cloud.githubusercontent.com/assets/805749/12306918/759670b4-ba23-11e5-83a2-d5c535521a8a.png)

**Comment by rochacbruno** [comment]
@jfunez na verdade o retorno deveria ser o mesmo para as 3 variações de paths

```
/<string:name>/<path:id>/
/<name>/<path:id>/ 
/<string:name>/<id>/

/{name}/{id}/
/{name}/{id}/ 
/{name}/{id}/
```

**Comment by alephmelo** [comment]
Bruno, acho que na parte em que você obriga a ter o literal **:**  da regex ```(<(.*?\:)?(.*?)>)``` ele sempre vai procurar um **\\:** no primeiro grupo de match, o que torna greedy. Talvez precise de uma expressão mais elaborada.

Eu fiz essa usando método de negação:

```
(<([^<>]*:)?([^<>]*)>)
```
![capturar](https://cloud.githubusercontent.com/assets/6146240/12310909/018984b8-ba32-11e5-87fb-a7bb8b655d6f.PNG)

**Comment by rochacbruno** [comment]
@alephmelo :+1: Nice! Issue fixed!
It works even with more paths https://regex101.com/r/gZ2rV3/2
