### ISSUE TITLE
Support vendor extensions

### ISSUE THREAD

**Issue by DanCardin** [rochacbruno/flasgger#100]
I was going to write a minimal PR for doing this, but I wasn't sure how your test setup works in order to write a minimal test for this

Also I only care about doing this at the top level (to support x-groupTag with reDoc as a front-end template).

Basically, I inserted the below block right after the definition of `data` in `base.py` (~line 145)
```
        # Support extension properties in the top level config
        top_level_extension_options = get_vendor_extension_fields(self.config)
        if extension_options:
            data.update(top_level_extension_options)
```

and added the below block to `utils.py`
```
def get_vendor_extension_fields(mapping):
    return {key: value for key, value in mapping.items() if key.startswith('x-')}
```

**Comment by rochacbruno** [comment]
@DanCardin 

The test setup is very simple, you write an application under `/examples` folder and the app will run in travis so you can write a function `test_swag` to test anything you want.

Look the exemple: https://github.com/rochacbruno/flasgger/blob/master/examples/colors.py#L76

I like the idea, so if you can send a PR would be very nice.
