### ISSUE TITLE
Upgrade version of swagger-ui

### ISSUE THREAD

**Issue by mrfuxi** [rochacbruno/flasgger#119]
UI v3 was added just before swagger-ui version 3 was released, now the current version is 3.0.16

**Comment by neumannrf** [comment]
Is the purpose of this issue to update the look and feel of flasgger-created `/apidocs/` from [the old style](http://flasgger.pythonanywhere.com/example_app/apidocs/#/users) to [the new style](http://petstore.swagger.io/)?

**Comment by mrfuxi** [comment]
I guess, basically use up to date version of `https://github.com/swagger-api/swagger-ui`

**Comment by MaciejKucia** [comment]
I think this issue can be closed :smiley:
