### ISSUE TITLE
[Question] Can you just run the UI from a single external YAML?

### ISSUE THREAD

**Issue by fdosani** [rochacbruno/flasgger#126]
Hi there, 

First off great project! Just a general question. Not sure if this is the same as issue #88 
I'm using the `flask-restful` and would like to define my API externally in a YAML file and just use flassger to run the UI portion. I can't get it to work exactly. Is this even possible?

It seems to work fine if I'm writing YAML in the docstring similar to the example in the `README`: https://github.com/rochacbruno/flasgger#using-flask-restful-resources

I have multiple `Resource` classes in separate modules which define my endpoints but ideally I'd just like one YAML which documents it all.

Thanks!

**Comment by rochacbruno** [comment]
Take a look at this example:

https://github.com/rochacbruno/flasgger/blob/master/examples/colors_template.yaml
and
https://github.com/rochacbruno/flasgger/blob/master/examples/colors_template_yaml.py 

In that example you have a single YAML describing all paths.

**Comment by fdosani** [comment]
@rochacbruno Thank you. I was probably over thinking it. Got it working for my use case. 👍
