### ISSUE TITLE
Restrict Access to Swagger UI

### ISSUE THREAD

**Issue by benjohnsonnlp** [rochacbruno/flasgger#132]
I'd like to be able to 401 on accesses to the swagger UI that don't have the correct credentials in their headers.  Is there currently a way to do this in flasgger, or is it something that needs to be added?

**Comment by allrod5** [comment]
You can restrict access to flasgger endpoints with a guard function registered to `Flask::before_request`:

```python
    from http import HTTPStatus # Python 3
    import os
    import re
    from flask import abort
    from flask import request

    def guard_apidocs_requests(app):
        api_key = os.getenv('SWAGGER_API_KEY')
        pattern = re.compile('flasgger\.(.*)')

        if api_key is None:
            raise KeyError('SWAGGER_API_KEY environment variable is not set')

        def check_api_key():
            if not pattern.match(str(request.endpoint)):
                return

            if request.args.get('api_key') == api_key:
                return

            abort(HTTPStatus.NOT_FOUND)

        app.before_request(check_api_key)
```

**Comment by allrod5** [comment]
The caveat with this approach is that SwaggerUI won't just work as it will attempt accessing `/jsonspecs_1.json` without an API key. To make it work you'll have to manually append query parameter `?api_key=MY_API_KEY_HERE` for the JSON URL within the SwaggerUI explorer bar. Adding the api_key automatically is a feature flasgger does not provide yet.

If you want not to have this extra step then you would have to serve your own SwaggerUI supporting api_keys.

Personally, I prefer serving my own SwaggerUI for production code and let the development builds with the APIs and API docs unprotected for ease of testing.

**Comment by benjohnsonnlp** [comment]
Great, I'll give this a try. Thanks!
