### ISSUE TITLE
HTTPS  is not supported in the current flasgger version 

### ISSUE THREAD

**Issue by pint12** [rochacbruno/flasgger#134]
it seems that there is an issue regarding the HTTPS  for swagger ui that was solved in more advanced version 
https://github.com/swagger-api/swagger-ui/issues/3166

so currently flasgger also does not support the HTTPS  api requests .

**Comment by rochacbruno** [comment]
Ok, so it is time to update the swagger UI, will do that today

**Comment by VjSng** [comment]
@rochacbruno. Thanks for the quick response on the issue. But by what time we shall expect the fix of this issue ?

**Comment by rochacbruno** [comment]
@VjSng swagger UI updated and released, please test it and if ok pelase close this issue

**Comment by VjSng** [comment]
@rochacbruno. I am still facing the same issue even though I have updated flasgger to the latest version i.e. 0.6.6. 
![l_172c tmp](https://user-images.githubusercontent.com/30320963/28527765-33f45c5a-70a9-11e7-8acf-3a42573b5ab1.png)

I am using these settings. Even though the schemes tag has only "https", I am unable to use https request type in flasgger.

`template = {
  "swagger": "2.0",
  "info": {
    "title": "API ",
    "description": "list of API that can used from external service",
    "contact": {
      "responsibleOrganization": "AIO",
      "responsibleDeveloper": "TBD",
    },
    "termsOfService": "TBD",
    "version": str(dpm_version)
  },
  "schemes": [
    [
           "https"
    ]
  ],
  "operationId": "getmyData"
}`

**Comment by VjSng** [comment]
@rochacbruno. I have just upgraded from 0.6.5 to 0.6.6. Is this the version which has the Fix ?

**Comment by rochacbruno** [comment]
@VjSng yes 0.6.6 has the latest swagger-ui

**Comment by allrod5** [comment]
@VjSng Does the fix you mentioned was released for SwaggerUI 2? Give SwaggerUI 3 a try:
```python
app = Flask(__name__)
app.config['SWAGGER'] = {
    'title': 'API',
    'uiversion': 3
}
swagger = Swagger(app)
```

**Comment by allrod5** [comment]
@VjSng Yet, `"schemes": [ [ "https" ] ]` shouldn't be `"schemes": [ "https" ]`?

**Comment by VjSng** [comment]
@rochacbruno  and @allrod5. Thanks it's working fine now :)

**Comment by rochacbruno** [comment]
@VjSng jsut for the record, it was a problem with `"schemes": [ "https" ]`? or are you using `ui: 3` ?

**Comment by VjSng** [comment]
@rochacbruno The problem was with the ui:3.

**Comment by javabrett** [comment]
This is working for me for both http and https, for both ui2 and ui3.  Based on that I'm closing the issue - @pint12 and others please reopen if this remains an issue.  /cc @rochacbruno .
