### ISSUE TITLE
ImportError: No module named flasgger

### ISSUE THREAD

**Issue by mayurjain0312** [rochacbruno/flasgger#139]
I did the following:
sudo pip --no-cache-dir install flasgger

/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py:1874: UserWarning: /usr/lib/pymodules/python2.7/rpl-1.5.5.egg-info could not be properly decoded in UTF-8
  warnings.warn(msg)
Requirement already satisfied: flasgger in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: PyYAML>=3.0 in /usr/lib/python2.7/dist-packages (from flasgger)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from flasgger)
Requirement already satisfied: jsonschema>=2.5.1 in /usr/local/lib/python2.7/dist-packages (from flasgger)
Requirement already satisfied: mistune in /usr/local/lib/python2.7/dist-packages (from flasgger)
Requirement already satisfied: Flask>=0.10 in /usr/local/lib/python2.7/dist-packages (from flasgger)
Requirement already satisfied: functools32; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from jsonschema>=2.5.1->flasgger)
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.10->flasgger)
Requirement already satisfied: Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from Flask>=0.10->flasgger)
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.10->flasgger)
Requirement already satisfied: click>=2.0 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.10->flasgger)
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

When I ran the python app that uses flasgger, I get the following error:
File "mayur_swagger_experiments/mayur_swagger_yml_app.py", line 3, in <module>
    from flasgger import Swagger
ImportError: No module named flasgger

**Comment by rochacbruno** [comment]
Looks like you have something wrong in your local python installation, also it is not recomended to use `sudo` to install dependencies, and when used `-H -U` should be passed. 

```bash
brunorocha.org@new-host:~/P/robottelo|master⚡?
➤ vf tmp --python=python2.7                                                                                                                           22:27:33
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/brocha/.virtualenvs/tempenv-15a127331723d/bin/python2.7
Also creating executable in /home/brocha/.virtualenvs/tempenv-15a127331723d/bin/python
Installing setuptools, pip, wheel...done.
brunorocha.org@new-host(tempenv-15a127331723d) :~/P/robottelo|master⚡?
➤ pip --no-cache-dir install flasgger                                                                                                                 22:27:39
Collecting flasgger
  Downloading flasgger-0.6.6-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.9MB 11.8MB/s 
Collecting PyYAML>=3.0 (from flasgger)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 9.2MB/s 
Collecting six>=1.10.0 (from flasgger)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting jsonschema>=2.5.1 (from flasgger)
  Downloading jsonschema-2.6.0-py2.py3-none-any.whl
Collecting mistune (from flasgger)
  Downloading mistune-0.7.4-py2.py3-none-any.whl
Collecting Flask>=0.10 (from flasgger)
  Downloading Flask-0.12.2-py2.py3-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 12.2MB/s 
Collecting functools32; python_version == "2.7" (from jsonschema>=2.5.1->flasgger)
  Downloading functools32-3.2.3-2.zip
Collecting itsdangerous>=0.21 (from Flask>=0.10->flasgger)
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 33.6MB/s 
Collecting Jinja2>=2.4 (from Flask>=0.10->flasgger)
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 12.3MB/s 
Collecting Werkzeug>=0.7 (from Flask>=0.10->flasgger)
  Downloading Werkzeug-0.12.2-py2.py3-none-any.whl (312kB)
    100% |████████████████████████████████| 317kB 14.6MB/s 
Collecting click>=2.0 (from Flask>=0.10->flasgger)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 11.3MB/s 
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->Flask>=0.10->flasgger)
  Downloading MarkupSafe-1.0.tar.gz
Installing collected packages: PyYAML, six, functools32, jsonschema, mistune, itsdangerous, MarkupSafe, Jinja2, Werkzeug, click, Flask, flasgger
  Running setup.py install for PyYAML ... done
  Running setup.py install for functools32 ... done
  Running setup.py install for itsdangerous ... done
  Running setup.py install for MarkupSafe ... done
Successfully installed Flask-0.12.2 Jinja2-2.9.6 MarkupSafe-1.0 PyYAML-3.12 Werkzeug-0.12.2 click-6.7 flasgger-0.6.6 functools32-3.2.3.post2 itsdangerous-0.24 jsonschema-2.6.0 mistune-0.7.4 six-1.10.0
brunorocha.org@new-host(tempenv-15a127331723d) :~/P/robottelo|master⚡?
➤ python -c 'from flasgger import Swagger'                                                                                                            22:27:48
brunorocha.org@new-host(tempenv-15a127331723d) :~/P/robottelo|master⚡?
➤                                                                         
```

**Comment by mayurjain0312** [comment]
Hi,

I did a pip uninstall first:
sudo pip uninstall flasgger
/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py:1874: UserWarning: /usr/lib/pymodules/python2.7/rpl-1.5.5.egg-info could not be properly decoded in UTF-8
  warnings.warn(msg)
The directory '/usr2/mayurj/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling flasgger-0.6.6:
  /usr/local/lib/python2.7/dist-packages/demo_app/__init__.py
  /usr/local/lib/python2.7/dist-packages/demo_app/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/demo_app/app.py
  /usr/local/lib/python2.7/dist-packages/demo_app/app.pyc
  /usr/local/lib/python2.7/dist-packages/examples/__init__.py
  /usr/local/lib/python2.7/dist-packages/examples/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/examples/apispec_example.py
  /usr/local/lib/python2.7/dist-packages/examples/apispec_example.pyc
  /usr/local/lib/python2.7/dist-packages/examples/base_model_view.py
  /usr/local/lib/python2.7/dist-packages/examples/base_model_view.pyc
  /usr/local/lib/python2.7/dist-packages/examples/basic_auth.py
  /usr/local/lib/python2.7/dist-packages/examples/basic_auth.pyc
  /usr/local/lib/python2.7/dist-packages/examples/colors.py
  /usr/local/lib/python2.7/dist-packages/examples/colors.pyc
  /usr/local/lib/python2.7/dist-packages/examples/colors_from_specdict.py
  /usr/local/lib/python2.7/dist-packages/examples/colors_from_specdict.pyc
  /usr/local/lib/python2.7/dist-packages/examples/colors_template_json.py
  /usr/local/lib/python2.7/dist-packages/examples/colors_template_json.pyc
  /usr/local/lib/python2.7/dist-packages/examples/colors_template_yaml.py
  /usr/local/lib/python2.7/dist-packages/examples/colors_template_yaml.pyc
  /usr/local/lib/python2.7/dist-packages/examples/colors_with_schema.py
  /usr/local/lib/python2.7/dist-packages/examples/colors_with_schema.pyc
  /usr/local/lib/python2.7/dist-packages/examples/compat.py
  /usr/local/lib/python2.7/dist-packages/examples/compat.pyc
  /usr/local/lib/python2.7/dist-packages/examples/custom_validation_function.py
  /usr/local/lib/python2.7/dist-packages/examples/custom_validation_function.pyc
  /usr/local/lib/python2.7/dist-packages/examples/decorator_package.py
  /usr/local/lib/python2.7/dist-packages/examples/decorator_package.pyc
  /usr/local/lib/python2.7/dist-packages/examples/definition_object_test.py
  /usr/local/lib/python2.7/dist-packages/examples/definition_object_test.pyc
  /usr/local/lib/python2.7/dist-packages/examples/disable_swagger_ui.py
  /usr/local/lib/python2.7/dist-packages/examples/disable_swagger_ui.pyc
  /usr/local/lib/python2.7/dist-packages/examples/example_app.py
  /usr/local/lib/python2.7/dist-packages/examples/example_app.pyc
  /usr/local/lib/python2.7/dist-packages/examples/example_blueprint.py
  /usr/local/lib/python2.7/dist-packages/examples/example_blueprint.pyc
  /usr/local/lib/python2.7/dist-packages/examples/get_schema.py
  /usr/local/lib/python2.7/dist-packages/examples/get_schema.pyc
  /usr/local/lib/python2.7/dist-packages/examples/marshmallow_apispec.py
  /usr/local/lib/python2.7/dist-packages/examples/marshmallow_apispec.pyc
  /usr/local/lib/python2.7/dist-packages/examples/no_routes.py
  /usr/local/lib/python2.7/dist-packages/examples/no_routes.pyc
  /usr/local/lib/python2.7/dist-packages/examples/package_example.py
  /usr/local/lib/python2.7/dist-packages/examples/package_example.pyc
  /usr/local/lib/python2.7/dist-packages/examples/restful.py
  /usr/local/lib/python2.7/dist-packages/examples/restful.pyc
  /usr/local/lib/python2.7/dist-packages/examples/specs_route_example.py
  /usr/local/lib/python2.7/dist-packages/examples/specs_route_example.pyc
  /usr/local/lib/python2.7/dist-packages/examples/top_level_vendor_extension.py
  /usr/local/lib/python2.7/dist-packages/examples/top_level_vendor_extension.pyc
  /usr/local/lib/python2.7/dist-packages/examples/validation.py
  /usr/local/lib/python2.7/dist-packages/examples/validation.pyc
  /usr/local/lib/python2.7/dist-packages/flasgger-0.6.6.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/flasgger-0.6.6.dist-info/INSTALLER
  /usr/local/lib/python2.7/dist-packages/flasgger-0.6.6.dist-info/METADATA
  /usr/local/lib/python2.7/dist-packages/flasgger-0.6.6.dist-info/RECORD
  /usr/local/lib/python2.7/dist-packages/flasgger-0.6.6.dist-info/WHEEL
  /usr/local/lib/python2.7/dist-packages/flasgger-0.6.6.dist-info/metadata.json
  /usr/local/lib/python2.7/dist-packages/flasgger-0.6.6.dist-info/top_level.txt
  /usr/local/lib/python2.7/dist-packages/flasgger/__init__.py
  /usr/local/lib/python2.7/dist-packages/flasgger/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/flasgger/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python2.7/dist-packages/flasgger/__pycache__/base.cpython-36.pyc
  /usr/local/lib/python2.7/dist-packages/flasgger/__pycache__/constants.cpython-36.pyc
  /usr/local/lib/python2.7/dist-packages/flasgger/__pycache__/marshmallow_apispec.cpython-36.pyc
  /usr/local/lib/python2.7/dist-packages/flasgger/__pycache__/utils.cpython-36.pyc
  /usr/local/lib/python2.7/dist-packages/flasgger/base.py
  /usr/local/lib/python2.7/dist-packages/flasgger/base.pyc
  /usr/local/lib/python2.7/dist-packages/flasgger/constants.py
  /usr/local/lib/python2.7/dist-packages/flasgger/constants.pyc
  /usr/local/lib/python2.7/dist-packages/flasgger/marshmallow_apispec.py
  /usr/local/lib/python2.7/dist-packages/flasgger/marshmallow_apispec.pyc
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/css/print.css
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/css/reset.css
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/css/screen.css
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/css/style.css
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/css/typography.css
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/DroidSans-Bold.ttf
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/DroidSans.ttf
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/droid-sans-v6-latin-700.eot
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/droid-sans-v6-latin-700.svg
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/droid-sans-v6-latin-700.ttf
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/droid-sans-v6-latin-700.woff
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/droid-sans-v6-latin-700.woff2
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/droid-sans-v6-latin-regular.eot
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/droid-sans-v6-latin-regular.svg
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/droid-sans-v6-latin-regular.ttf
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/droid-sans-v6-latin-regular.woff
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/fonts/droid-sans-v6-latin-regular.woff2
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/images/collapse.gif
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/images/expand.gif
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/images/explorer_icons.png
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/images/favicon-16x16.png
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/images/favicon-32x32.png
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/images/favicon.ico
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/images/logo_small.png
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/images/pet_store_api.png
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/images/throbber.gif
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/images/wordnik_api.png
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/index.html
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/ca.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/el.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/en.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/es.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/fr.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/geo.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/it.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/ja.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/ko-kr.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/pl.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/pt.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/ru.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/tr.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/translator.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lang/zh-cn.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/backbone-min.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/es5-shim.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/handlebars-4.0.5.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/highlight.9.1.0.pack.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/highlight.9.1.0.pack_extended.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/jquery-1.8.0.min.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/jquery.ba-bbq.min.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/jquery.slideto.min.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/jquery.wiggle.min.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/js-yaml.min.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/jsoneditor.min.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/lodash.min.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/marked.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/object-assign-pollyfill.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/sanitize-html.min.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/lib/swagger-oauth.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/o2c.html
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/swagger-ui.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/static/swagger-ui.min.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/templates/flasgger/index.html
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/templates/flasgger/index_old.html
  /usr/local/lib/python2.7/dist-packages/flasgger/ui2/templates/flasgger/o2c.html
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/favicon-16x16.png
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/favicon-32x32.png
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/index.html
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/oauth2-redirect.html
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/swagger-ui-bundle.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/swagger-ui-bundle.js.map
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/swagger-ui-standalone-preset.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/swagger-ui-standalone-preset.js.map
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/swagger-ui.css
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/swagger-ui.css.map
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/swagger-ui.js
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/static/swagger-ui.js.map
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/templates/flasgger/index.html
  /usr/local/lib/python2.7/dist-packages/flasgger/ui3/templates/flasgger/oauth2-redirect.html
  /usr/local/lib/python2.7/dist-packages/flasgger/utils.py
  /usr/local/lib/python2.7/dist-packages/flasgger/utils.pyc
Proceed (y/n)? y
  Successfully uninstalled flasgger-0.6.6
The directory '/usr2/mayurj/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning


and did a pip install again:

sudo pip --no-cache-dir install flasgger
/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py:1874: UserWarning: /usr/lib/pymodules/python2.7/rpl-1.5.5.egg-info could not be properly decoded in UTF-8
  warnings.warn(msg)
Collecting flasgger
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading flasgger-0.6.6-py2.py3-none-any.whl (1.8MB)
    100% |################################| 1.9MB 43.4MB/s 
Requirement already satisfied: PyYAML>=3.0 in /usr/lib/python2.7/dist-packages (from flasgger)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from flasgger)
Requirement already satisfied: jsonschema>=2.5.1 in /usr/local/lib/python2.7/dist-packages (from flasgger)
Requirement already satisfied: mistune in /usr/local/lib/python2.7/dist-packages (from flasgger)
Requirement already satisfied: Flask>=0.10 in /usr/local/lib/python2.7/dist-packages (from flasgger)
Requirement already satisfied: functools32; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from jsonschema>=2.5.1->flasgger)
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.10->flasgger)
Requirement already satisfied: Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from Flask>=0.10->flasgger)
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.10->flasgger)
Requirement already satisfied: click>=2.0 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.10->flasgger)
Installing collected packages: flasgger
Successfully installed flasgger-0.6.6
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning


Do you find something wrong here?

**Comment by mayurjain0312** [comment]
@ rochacbruno : Thanks for your response.
I found the problem, it was with my way of installing flasgger.

**Comment by rreexxllii0310** [comment]
So, how do you solve the problem?
I have the same problem, and I use virtualenv with python 3.6 and use `pip install flasgger`

After pip install:
```
Requirement already satisfied: flasgger in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (0.9.5)
Requirement already satisfied: mistune in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from flasgger) (0.8.4)
Requirement already satisfied: jsonschema>=3.0.1 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from flasgger) (3.2.0)
Requirement already satisfied: Flask>=0.10 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from flasgger) (2.0.0)
Requirement already satisfied: PyYAML>=3.0 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from flasgger) (5.4.1)
Requirement already satisfied: six>=1.10.0 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from flasgger) (1.16.0)
Requirement already satisfied: Jinja2>=3.0 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from Flask>=0.10->flasgger) (3.0.1)
Requirement already satisfied: itsdangerous>=2.0 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from Flask>=0.10->flasgger) (2.0.1)
Requirement already satisfied: Werkzeug>=2.0 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from Flask>=0.10->flasgger) (2.0.1)
Requirement already satisfied: click>=7.1.2 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from Flask>=0.10->flasgger) (8.0.1)
Requirement already satisfied: importlib-metadata in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from click>=7.1.2->Flask>=0.10->flasgger) (4.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from Jinja2>=3.0->Flask>=0.10->flasgger) (2.0.1)
Requirement already satisfied: attrs>=17.4.0 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from jsonschema>=3.0.1->flasgger) (21.2.0)
Requirement already satisfied: setuptools in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from jsonschema>=3.0.1->flasgger) (50.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from jsonschema>=3.0.1->flasgger) (0.17.3)
Requirement already satisfied: dataclasses in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from Werkzeug>=2.0->Flask>=0.10->flasgger) (0.8)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from importlib-metadata->click>=7.1.2->Flask>=0.10->flasgger) (3.10.0.0)
Requirement already satisfied: zipp>=0.5 in /home/iottalk/iottalk-python3.6-venv/lib/python3.6/site-packages (from importlib-metadata->click>=7.1.2->Flask>=0.10->flasgger) (3.4.1)
```

And I ran my python code, it gave:
```
Traceback (most recent call last):
  File "/home/iottalk/iottalk/lib/csm.py", line 33, in <module>
    from flasgger import Swagger
ImportError: No module named 'flasgger'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
```

How can I do?

**Comment by Yakamoko** [comment]
Hi there,
Im trying to import flasgger aswell but cannot make it work. I am using the pip install command on a WSL2 subsystem linux distro on windows10. 
Im getting an error that couldnt find the version that satisfies the requiremnet and that there is no matching distribution for flasgger.
Anyone solved the problem somehow?

**Comment by vaibhav251999** [comment]
same here same problem not able to import flasggar
