### ISSUE TITLE
Move development pip packages to separate requirements.txt

### ISSUE THREAD

**Issue by JoakimSoderberg** [rochacbruno/flasgger#145]
Currently things like coveralls and unit tests files are included in the `requirements.txt`. The only way these extra packages only used for unit tests and development are separated are via a comment.

Why not break these out into a separate `requirements-dev.txt` instead? Then when one wants to develop or run unit tests one can install these extra packages:

Normal use:
```bash
pip install  # Uses requirements.txt by default.
```

Then during development one can install the extra dev packages:
```bash
pip install
pip install -r requirements-dev.txt  # Installs the extra dev only packages
```

**Comment by rochacbruno** [comment]
I am ok with this if you can send a PR and also fix travis CI to also isntal this new file.

But note that you only need requirements.txt for development, because `python setup.py install` already installs everything from https://github.com/rochacbruno/flasgger/blob/master/setup.py#L47

**Comment by JoakimSoderberg** [comment]
Done:
https://github.com/rochacbruno/flasgger/pull/149
