### ISSUE TITLE
Supporting requestBody in Swagger UI v3

### ISSUE THREAD

**Issue by hunt3ri** [rochacbruno/flasgger#157]
Hi

I was experimenting with UI v3, and it looks like it doesn't support the new [requestBody object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#requestBodyObject).  What, if any, plans do you have to support the Swagger 3 spec?

Thanks
Iain

**Comment by rochacbruno** [comment]
That would be nice to have it! 
I'll wait for a PR from any of contributors (or start working on this when I got time)
