### ISSUE TITLE
Parameters are not viewable in apidocs view

### ISSUE THREAD

**Issue by leelu** [rochacbruno/flasgger#164]
Hi,

When parameters for specific HTTP methods are given, then in **apidocs view** the parameters are not showing up. Below is an example that i was trying. To fix this I have done a small change in base.py at line number 201, I have added below code after line 201

```
http_methods = ['get', 'post', 'put', 'del']
if verb in swag.keys():
    verb_swag = swag.get(verb)
    if len(params) == 0 and verb.lower() in http_methods:
        params = verb_swag.get('parameters', [])

```
Is this fine to fix this issue ?
ex:
[https://pastebin.com/ghAq3LEU](url)

**Comment by rochacbruno** [comment]
can you send a Pull Request please?

**Comment by leelu** [comment]
Fix merged to the code
