### ISSUE TITLE
Smarter merging of specs_dict

### ISSUE THREAD

**Issue by Teyras** [rochacbruno/flasgger#172]
I tried implementing a custom decorator that autofills some repetitive documentation data using the `specs_dict` attribute on the decorated function (this is also used by `@swag_from`). However, because of [this line](https://github.com/rochacbruno/flasgger/blob/8adba148ec4b262ac304b8439e10f55ef521c285/flasgger/utils.py#L110), some of my autofilled data gets overwritten by data in the docblock. For example, if `specs_dict` contains `responses: {403: ...}` and my docblock has `responses: {200: ...}`, I would like the result to contain both of the responses.

Do you have any thoughts on this? If there's nothing wrong with this feature, I'm willing to implement it.

**Comment by allrod5** [comment]
Despite I am not the one who wrote the code you reference (git blame points my user because I moved this function to where it is now) feel free to implement the feature, as long tests passes it shouldn't break anything.

**Comment by Teyras** [comment]
Can I get a review on my PR, please?
