### ISSUE TITLE
TemplateNotFound: flasgger/index.html

### ISSUE THREAD

**Issue by Mallouly** [rochacbruno/flasgger#188]
hi,
I tried to add flasgger to my restful api.
i used yaml files for each method but when I'm trying to see the documentation  at localhost:port/apidocs I getting the following error:
jinja2.exceptions.TemplateNotFound: flasgger/index.html

any suggestion?

thanks in advance

**Comment by akhilbatra898** [comment]
How did you solve it?

**Comment by RafalChlopek** [comment]
same problem here and I'm stuck. Anyone knows hot to fix it?

**Comment by octsobral** [comment]
Same problem here! Anyone with an answer?
