### ISSUE TITLE
Request: release a new version (0.8.2?) with the latest bug fixes

### ISSUE THREAD

**Issue by abstiles** [rochacbruno/flasgger#194]
Please publish a new release of Flasgger. I am currently relying on a local build of this repository at a fixed commit, and it would be nice to resume using an official release. Thank you!

**Comment by rochacbruno** [comment]
Will do by the weekend, I'll run some integration tests and upgrade tests on my apps.

@allrod5 something else you think is missing to a new release?

**Comment by allrod5** [comment]
@rochacbruno I think it's fine to publish a new release :+1:
