### ISSUE TITLE
/package_example/apidocs/ fails with INTERNAL SERVER ERROR /package_example/apispec_1.json

### ISSUE THREAD

**Issue by javabrett** [rochacbruno/flasgger#206]
Navigating to http://flasgger.pythonanywhere.com/package_example/apidocs/ (as linked from index page) produces:

```
Failed to load API definition.
Fetch error
INTERNAL SERVER ERROR /package_example/apispec_1.json
```

**Comment by javabrett** [comment]
This issue is caused by the _flasgger.pythonanywhere.com_ deployment not having the `marshmallow` package installed (at all), because it is only in [requirements-dev.txt](https://github.com/rochacbruno/flasgger/blob/a4340b799847886fcc637db15eba095062a452e5/requirements-dev.txt#L2) and not in [setup.py](https://github.com/rochacbruno/flasgger/blob/a4340b799847886fcc637db15eba095062a452e5/setup.py#L48) (or [requirements.txt](https://github.com/rochacbruno/flasgger/blob/a4340b799847886fcc637db15eba095062a452e5/requirements.txt)).

I propose adding an optional extras to _setup.py_.  Then to fully resolve, the _pythonanywhere_ deployment scripts will need an update (I don't think those are currently in the project).

**Comment by javabrett** [comment]
This was fixed during recent release re-deployments.  Virtual env on pythonanywhere was rebuilt including optional/dev dependencies.

_setup.py_ work mentioned above should probably be done eventually, but this issue itself is fixed so closing.

**Comment by gennaro-tedesco** [comment]
I am seeing the same problem: what is the preferred solution?

**Comment by billyrrr** [comment]
@gennaro-tedesco does the current master branch create the same problem?

**Comment by gennaro-tedesco** [comment]
yes, it does. Is there a specified way to maybe install some particular commits where the fix where done (if at all)? Both forcing to install the current master branch or using `pipenv` to create virtual environments generate the same problem.

**Comment by billyrrr** [comment]
Could you paste the stacktrace / error report generated from running the code? I need more information to find out the problem.

**Comment by gennaro-tedesco** [comment]
The error is exactly the same as specified in the original post here:

```
Failed to load API definition.
Fetch error
INTERNAL SERVER ERROR /package_example/apispec_1.json
```

this happens when I use the decorator `@swag_from('filename')` - whereas it does not happen otherwise (if I specify the docstring instead).

**Comment by billyrrr** [comment]
The behavior of ```swag_from``` and docstring ```import:``` are different. This is expected behavior. However, it can be made better. Could you submit a new issue based on the difference of behavior between ```swag_from``` and docstring ```import:```? Your error should have its own issue since the error under this issue was caused by a different reason (marshmallow not imported).

**Comment by gennaro-tedesco** [comment]
I will do, thank you for clarifying.

**Comment by raquelfleeet** [comment]
@gennaro-tedesco did u manage to solve the issue with swag_from? thank you

**Comment by raquelfleeet** [comment]
> I will do, thank you for clarifying.

Hi did u manage to solve this issue?

**Comment by scheung38** [comment]
Hello, I am still seeing this issue, is this resolved now?

<img width="1152" alt="Screenshot 2023-05-31 at 19 56 20" src="https://github.com/flasgger/flasgger/assets/1273014/9ebf8d39-6f5d-4823-bde7-1670b83efbc5">

**Comment by karkir0003** [comment]
@scheung38 I'm having this issue right now. Were you able to resolve?

**Comment by niteshsilwal01** [comment]
I tried the following and it worked for me.

from werkzeug.utils import secure_filename
filename = secure_filename(request.files['file'].filename)
file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

In this example, secure_filename is used to secure the filename of the uploaded file before it's saved to the filesystem.
