### ISSUE TITLE
Hardcoded optional_fields

### ISSUE THREAD

**Issue by vovanz** [rochacbruno/flasgger#21]
[Optional fields for operation definition are hardcoded.](https://github.com/rochacbruno/flasgger/blob/master/flasgger/base.py#L228)

So, if you want to add some non-standard fields (I want to generate swagger definition for Amazon API Gateway, so I have to use [their extensions to swagger](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html)) you have to patch it, using inheritance or monkey-patching.

It is very inconvenient. I suggest to allow overwriting this list in config or just allow using any optional fields without any filtering (maybe by adding to config "strict"/"non-strict" switcher, where "non-strict" will mean that any optional fields are allowed).

**Comment by rochacbruno** [comment]
optional_fields is now read from app.config['SWAGGER']
