### ISSUE TITLE
Import of apispec.ext.marshmallow.swagger fail due to breaking change in apispec

### ISSUE THREAD

**Issue by xeroc** [rochacbruno/flasgger#219]
According to [apispec/Changelog](https://github.com/marshmallow-code/apispec/blob/dev/CHANGELOG.rst#0390-2018-06-28)

> [apispec.core]: Backwards-incompatible: Change plugin interface. Plugins are now child classes of apispec.BasePlugin. Built-in plugins are still usable with the deprecated legacy interface. However, the new class interface is mandatory to pass parameters to plugins or to access specific methods that used to be accessed as module level functions (typically in apispec.ext.marshmallow.swagger). Also, schema_name_resolver is now a parameter of apispec.ext.marshmallow.MarshmallowPlugin. It can still be passed to APISpec while using the legacy interface. (:issue:`207`)

The change results in [this example code](https://github.com/rochacbruno/flasgger#using-marshmallow-schemas) to throw the following error

> ModuleNotFoundError: No module named 'apispec.ext.marshmallow.swagger'

Given that I don't know enough of the internal functionalities, I cannot provide a Pull Request.

**Comment by rochacbruno** [comment]
This has been solved here https://github.com/rochacbruno/flasgger/pull/205 pending release.

**Comment by xeroc** [comment]
Thank you ... closing ticket
