### ISSUE TITLE
Resource Warning: unclosed file

### ISSUE THREAD

**Issue by rchacon1** [rochacbruno/flasgger#22]
I believe you need to close the yaml files:

https://github.com/rochacbruno/flasgger/blob/master/flasgger/base.py#L42
https://github.com/rochacbruno/flasgger/blob/master/flasgger/base.py#L45

**Comment by rochacbruno** [comment]
@rchacon1 ohh thanks.. that is a shame... need to put this in a with context.. 

Will look in to this or wait a PR
