### ISSUE TITLE
A way to parse request data and validate schema

### ISSUE THREAD

**Issue by strongbugman** [rochacbruno/flasgger#220]
Hi, I find a way to parse request`s data and validate schema, not only data in body can be validated, take a look at  [gist](https://gist.github.com/strongbugman/2c8e1cd9673ebdc59403a4055e4060c6), do you have any idea?

**Comment by rochacbruno** [comment]
I like the idea and implementation, I like the idea of having a standard directory structure to load the yamls, it would be nice also to load the specs and not only for validation.

If you want to send a PR integrating this to flasgger it is a nice idea.

**Comment by strongbugman** [comment]
Thanks for your suggestion，I'll send a PR after I am  familiar with flasgger`s base codes
