### ISSUE TITLE
Index url path

### ISSUE THREAD

**Issue by incognick** [rochacbruno/flasgger#23]
I can see the documentation if I type in /apidocs/index.html but it doesn't load if I only type in /apidocs.  Shouldn't it load from both? 

I looked down into the blueprint setup but I couldn't see how to get this to work.

**Comment by rochacbruno** [comment]
@incognick nice idea, should be simple to add in blueprint.

**Comment by rochacbruno** [comment]
Done

**Comment by incognick** [comment]
Thanks!
