### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'Str'

### ISSUE THREAD

**Issue by suifengpiao14** [rochacbruno/flasgger#230]
after apispec 0.38.0 version apispec/apispec/ext/marshmallow/swagger.py has moved，replace with openapi.py and common.py. so in file flasgger/marshmallow_apispec.py can not import schema2jsonschema, schema2parameters from apispec.ext.marshmallow.swagger ,
but i change  to import from apispec.ext.marshmallow.openapi also get error  ImportError: cannot import name schema2jsonschema

when i install apispec with 0.38.0 version  (pip install marshmallow apispec==0.38.0)  it's ok.
so I think it‘s time to update document “pip install marshmallow apispec” to “pip install marshmallow apispec==0.38.0”  or upgrade origin code to match apispec latest verson .

however,I'm so. I don't know how to do it .  I hope somebody can fix it when he(or she) have time.

**Comment by suifengpiao14** [comment]
oh,I see master branch has changed ,waitting for new tag^_^

**Comment by javabrett** [comment]
@suifengpiao14 looks like you found this already fixed on master, duplicates fix #205 .  Thanks for the report.
