### ISSUE TITLE
Is there any way to disable "try out" feature in flasgger?

### ISSUE THREAD

**Issue by fbiopereira** [rochacbruno/flasgger#233]
I have a REST API made with Flask and documented with flasgger and would like to disable "try out" feature in POST and PUT methods.

**Comment by rochacbruno** [comment]
Looks like it is not even possible in Swagger UI, you may need to write a JS plugin and then load in the templates/flasgger/index.html

https://github.com/swagger-api/swagger-ui/issues/3725

**Comment by javabrett** [comment]
If you are using ui3, could you just add a custom style to hide it?

```
.opblock-post .try-out {
  display: none;
}
```
... and repeat for `PUT`.

Of course this is only hiding/masking in the UI, but it's all UI anyway so you may need to secure those operations properly if you really don't want them called.

**Comment by javabrett** [comment]
@fbiopereira let me know if some custom CSS as suggested above works for you.

**Comment by fbiopereira** [comment]
Yes we tried and it worked.
But we decided to keep try out enabled for an while.
________________________________
De: Brett Randall <notifications@github.com>
Enviado: terça-feira, 4 de setembro de 2018 20:36
Para: rochacbruno/flasgger
Cc: fbiopereira; Mention
Assunto: Re: [rochacbruno/flasgger] Is there any way to disable "try out" feature in flasgger? (#233)


@fbiopereira<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffbiopereira&data=02%7C01%7C%7C2b1e321a5b744510938108d612bf4d4f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636717010171129237&sdata=LSl%2B4CLMnYMgRUh16d%2BBWGBT743Flwep6DD4DBFhbys%3D&reserved=0> let me know if some custom CSS as suggested above works for you.

**Comment by IreneMaryanne** [comment]
@fbiopereira @rochacbruno @javabrett 
You can specify which methods to show the "Try it out" button by  using "supportedSubmitMethods" attribute as documented in [swaggerConfigDoc](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/)
Go to your flasgger library templates installed path, e.g: 
`C:\Python27\Lib\site-packages\flasgger\ui3\templates\flasgger`
Edit **swagger.html**:

> window.onload = function() {
>   ...
>     // Build a system
>     const ui = SwaggerUIBundle(
>     Object.assign(
>     {
>     url: "{{ specs[0]['url'] }}",
>     dom_id: '#swagger-ui',
>     **supportedSubmitMethods: ['get'],**
> 
> ...

Just add the line `supportedSubmitMethods: ['get'],` inside Object.assign, like in my example, is below dom_id attribute.
You can add more methods to display the "Try it out" button besides 'get', e.g. 
`supportedSubmitMethods: ['get', 'fetch'],`

Cheers.

**Comment by caffeinatedMike** [comment]
@IreneMaryanne @rochacbruno Any chance you could draft up a Pull Request that has an additional conditional in the __swagger.html__ to allow for easily setting the `supportedSubmitMethods`? I imagine it would be something like this (psuedo-code, needs to be tested):

__swagger.html__
```
{% if flasgger_config.supported_submit_methods -%}
    supportedSubmitMethods: {{ supported_submit_methods|unique|list|lower }},
{%- endif %}
```

__flasgger_config__
```python3
app.config['SWAGGER'] = {
    'supported_submit_methods': ['Get','POST','get','Put','DELETE'],
   ...
}
```

This would be a nice custom feature to have.

**Comment by IreneMaryanne** [comment]
@caffeinatedMike Hi
You may want to look at this line in swagger.html
https://github.com/flasgger/flasgger/blob/master/flasgger/ui3/templates/flasgger/swagger.html#L59
I think you can use 'ui_params' as object key in flasgger_config.

Also this may be helpful
https://github.com/flasgger/flasgger#customize-default-configurations

**Comment by caffeinatedMike** [comment]
@IreneMaryanne Exactly what I was looking for. Thank you!

**Comment by RodrigoRosmaninho** [comment]
@IreneMaryanne thanks a lot!
