### ISSUE TITLE
Git tags add/fix/move releases 0.8.2 and 0.8.3

### ISSUE THREAD

**Issue by javabrett** [rochacbruno/flasgger#238]
Looks like there's a couple of tagging issues - historical, but probably worth fixing for reference.

- tag 0.8.3 points to 51bf02c74651b1a33b5789d8825ae691c8e23789 , but that is actually 0.8.2.  0.8.3 should reference the following-commit 3ed982163a4270075a5b41553db104008e8e834d .
- tag 0.8.2 is missing and should point to 51bf02c74651b1a33b5789d8825ae691c8e23789 where 0.8.3 currently points.  I think that release was mostly discarded and 0.8.3 immediately followed, but it's on PyPi, so we should probably tag it.

Also, any objections to using signed, annotated tags moving forward?

@rochacbruno for your review before I make these changes.

**Comment by rochacbruno** [comment]
+1 to use annotated tags

**Comment by javabrett** [comment]
Tags have been added/moved as discussed above.  Annotated and signed tags created.
