### ISSUE TITLE
Plugin support - Marshmallow

### ISSUE THREAD

**Issue by incognick** [rochacbruno/flasgger#24]
Is it possible to get Marshmallow integration?   I could possibly do this if someone pointed me in the right direction to add it: 

Similar to this project but Flasgger is better since it provides all the html (no secondary server is required)
https://github.com/marshmallow-code/apispec

**Comment by rochacbruno** [comment]
I guess it is in #40 someone need to try

**Comment by rochacbruno** [comment]
implemented. added new app in examples/
