### ISSUE TITLE
Deploy 0.9.1 to http://flasgger.pythonanywhere.com

### ISSUE THREAD

**Issue by javabrett** [rochacbruno/flasgger#240]
As an aside to this - I have been mucking with some pythonanywhere scripting.  There are quite a few limitations to be aware of, but provided you are willing to do some initial manual set-up, it is possible to fashion a semi CI/CD from Travis to pythonanywhere.  So it would be possible to host a flasgger-master.pythonanywhere.com if that were desirable.  This would make master always-testable/demoable via a hosted-deployment, in-between releases.

@rochacbruno contact me off-site if required to discuss pythonanywhere hosting set-up/options and if the above is of interest.

**Comment by javabrett** [comment]
https://flasgger.pythonanywhere.com/ is currently showing 0.9.0 or something of that era and <0.9.1, so if it is fetching nightly with cron, maybe it currently has the 0.9.0 tag checked-out, or there's some conflict or other issue causing it to not update.

Is it intended to be master/dev/CI/CD, or is it supposed to be locked at the latest GA release?

The proposals are:

- Push 0.9.1 at a minimum to https://flasgger.pythonanywhere.com/
- If CI/CD is supposed to deploy master there nightly and that can be made to work, then that's probably fine.
- If not, or if that site should be pinned to a release tag, then the proposal is to consider a CI/CD for master, probably also on pythonanywhere.
- The stuff I have doesn't rely on cron, it is triggered via Travis deploy-phase, using the reload API.  This requires some cleverness since the WSGI script has to look after the Git pull etc.
- Other stuff that may be of interest is attempts to have the CI/CD also properly look after virtualenv maintenance - not sure if the site is currently doing that manually.

**Comment by rochacbruno** [comment]
Hi @javabrett I like your proposal I'll send you the credentials for PythonAnywhere via e-mail.

**Comment by javabrett** [comment]
`0.9.2.dev0` (`master`) demo app deployed manually.  Some sort of automation may follow later.
