### ISSUE TITLE
Conflicting files due to installation of examples

### ISSUE THREAD

**Issue by dvzrv** [rochacbruno/flasgger#242]
There is a file conflict between flasgger and micawber, because both install files into the too generic path name examples.
For reference, please see [this Arch Linux bug](https://bugs.archlinux.org/task/60006) and this [bug with micawber](https://github.com/coleifer/micawber/issues/83).

As a solution, micawber and flasgger should either not install these examples at all, or if required into a unique directory (e.g. micawber-examples) or another system directory (e.g. on Linux: /usr/share/doc/python-micawber/examples, which is usually done by the packagers).

I will remove them for now to resolve the file conflict.

**Comment by rochacbruno** [comment]
I think it is a bug `examples` should not be installed. 

Thanks for reporting.

**Comment by rochacbruno** [comment]
the solution is a change in setup.py adding

```
packages=find_packages(
        exclude=['tests', 'tests.*', 'examples', 'examples.*', 'demo_app', 'demo_app.*']
    ),
```
