### ISSUE TITLE
Flasgger 0.9.1 does not reflect changes without restarting app

### ISSUE THREAD

**Issue by ab-gissupport** [rochacbruno/flasgger#249]
I'm using latest flasgger==0.9.1 and create documentation in Yaml files using `swag_from` decorator. Whenever I change something in Yaml file (major or very minor change, whatever) I need to restart Python app in order to get changes reflected on Flasgger UI. I think it's quite inconvenient - I see it worked well in flasgger==0.8.3 without reloading.

Here is my init:

```python
def create_swagger(app):
    template = {
        "openapi": '3.0.0',
        "info": {
            "title": "my title",
            "description": "my description",
            "contact": {
                "responsibleOrganization": "my org",
                "email": "my mail",
                "url": "my url"
            },
            "version": "1.0"
        },
        "basePath": "/",
        "schemes": [
            "http",
            "https"
        ],
        "operationId": "getmyData"
    }

    config = {
            "headers": [
        ],
        "specs": [
            {
                "endpoint": 'api',
                "route": '/api.json',
                "rule_filter": lambda rule: True,  # all in
                "model_filter": lambda tag: True,  # all in
            }
        ],
        "static_url_path": "/flasgger_static",
        "swagger_ui": True,
        "specs_route": "/docs"        
    }    

    return Swagger(app, template=template, config=config)
```

**Comment by rochacbruno** [comment]
HI, if you install `pip install flasgger==0.8.3` does it work as expected?
I think we may have added some caching stuff and then we need to have optional flag to disable it.

Are you seeing this using which Flask version? Flask server or external server (like a wsgi)?

**Comment by ab-gissupport** [comment]
Yes, with 0.8.3 it works. I'm using `flask==1.0.2`, with Flask development server.

**Comment by ab-gissupport** [comment]
Hi, it's strictly for development purposes - I'm creating documentation and I refresh the page to see if changes I did in Yaml file are OK.

**Comment by rochacbruno** [comment]
@strongbugman we can try to use the `DEBUG` flask, if flask in in debug mode then cache is disabled. What do you think?

**Comment by strongbugman** [comment]
@rochacbruno Sounds great, I'll  send a PR soon

**Comment by javabrett** [comment]
PR #250 .

**Comment by rochacbruno** [comment]
@ab-gissupport can you test the changes in master #250 and then close this issue if it works for you?

**Comment by ab-gissupport** [comment]
Yes, it does work for me now. Thanks for quick help everyone!
