### ISSUE TITLE
How to configure sorting?

### ISSUE THREAD

**Issue by kutoxinyi** [rochacbruno/flasgger#277]
What I want is order by tags......but default is order by path on page

**Comment by javabrett** [comment]
Are you trying to order operations - you can add an `operationsSorter` for that.

https://github.com/rochacbruno/flasgger/blob/37ee86401e7c6c30dd45ef258d2f51647c48ef8c/examples/changelog_090.py#L59

**Comment by kutoxinyi** [comment]
> Are you trying to order operations - you can add an `operationsSorter` for that.
> 
> [flasgger/examples/changelog_090.py](https://github.com/rochacbruno/flasgger/blob/37ee86401e7c6c30dd45ef258d2f51647c48ef8c/examples/changelog_090.py#L59)
> 
> Line 59 in [37ee864](/rochacbruno/flasgger/commit/37ee86401e7c6c30dd45ef258d2f51647c48ef8c)
> 
>      "operationsSorter" : (a, b) => a.get("path").localeCompare(b.get("path"))

Thanks!  operationsSorter works for apis in one tag.  tagsSorter works for sorting tags.
