### ISSUE TITLE
New version to add disable validator link

### ISSUE THREAD

**Issue by borjafpa** [rochacbruno/flasgger#28]
Hi,

I've noticed that the current version 0.5.12 does not include the following commit:
https://github.com/rochacbruno/flasgger/commit/431649931652cf5b9827527f96eddc716ace7eb8

Are you planning to generate a new release with it soon?

Thank you and regards

**Comment by rochacbruno** [comment]
released 0.5.13

**Comment by borjafpa** [comment]
@rochacbruno thank you!
