### ISSUE TITLE
Unable to create global definitions

### ISSUE THREAD

**Issue by klarsen73** [rochacbruno/flasgger#29]
Due to the use of 'id' for schemas $ref to a defined schema doesn't work.

When running example application 'example_app.py' you can see that the GET method (get /v1/users/{team_id}) using $ref to reference #/definitions/User returns ' [ null ]'

With the current implementation the reference should be done like this:
$ref: '#/definitions/should_be_v1_only_post_post_User'

but that seems to be odd if you would like to define "global" objects that can be used by more than one method.

**Comment by rochacbruno** [comment]
done in #40
