### ISSUE TITLE
Allow a custom specs url for Swagger UI

### ISSUE THREAD

**Issue by dylaan** [rochacbruno/flasgger#36]
My project has a standalone Flask server behind nginx at '/api'. I cannot register a specs endpoint at '/specs', only '/api/specs'. Would it make sense to use app.config['SWAGGER']['basePath'] to prepend 'specs_url' in SwaggerUI/index.html? I can edit this myself, but will lose changes when updating this package.

**Comment by rochacbruno** [comment]
Fixed, now blueprint sets the url and uses basePath
