### ISSUE TITLE
Static url path change

### ISSUE THREAD

**Issue by MarcelWokke** [rochacbruno/flasgger#41]
Thanks for the great work it works fine!

One thing I noticed when I tried to change the static url path from apidocs to for instance  'sampleUrl' by adding my own DEFAULT_CONFIG object to the constructor everything worked great. But due to a typo I noticed that in the index.html there is still a fixed path reference to /apidocs in this redirect function

function redirect_to(url){
54	      window.location.href = '/apidocs/index.html?url=' + url;

Maybe this is something to fix in a next version?

**Comment by ankitarya10** [comment]
facing the same issue, did you find a workaround @MarcelWokke .

**Comment by rochacbruno** [comment]
implemented getting from config.
