### ISSUE TITLE
conversion of swagger document format

### ISSUE THREAD

**Issue by mayankthp** [rochacbruno/flasgger#48]
Hi Bruno,
First of all thanks for this awesome library :)
I can see that the format flasgger requires is slightly different from the one used by swagger.
That works fine, but in order to test my apis through tools like soapui i need the swagger format. Is there a converter available i can use , files that are created or do i need to use my own?

cheers.

**Comment by rochacbruno** [comment]
@mayankthp flasgger uses the same format as Swagger. Can you point which differences did you find?

**Comment by rochacbruno** [comment]
Flasgger reads YAML and generates JSON, Both respecting OpenAPIspecs.
