### ISSUE TITLE
Import another yaml file

### ISSUE THREAD

**Issue by AminHP** [rochacbruno/flasgger#51]
Hello!
Thanks for this useful library.
I want to import another yaml file in my swagger specification. For example i have a file named _username_definitions.yml_. Now i want to import _bad_request.yml_ to specify a "bad request" response. 

How can i do something like that?
If there is no way, will it good idea to implement an _import_ property myself?

username_definitions.yml
```
This is the summary defined in yaml file
First line is the summary
All following lines until the hyphens is added to description
the format of the first lines until 3 hyphens will be not yaml compliant
but everything below the 3 hyphens should be.
---
tags:
  - users
parameters:
  - in: path
    name: username
    type: string
    required: true
responses:
  200:
    description: A single user item
    schema:
      id: rec_username
      properties:
        username:
          type: string
          description: The name of the user
          default: 'steve-harris'

  import: "bad_request.yml" 
```

bad_request.yml

```
400:
  description: Bad request
```

**Comment by AminHP** [comment]
Are u there?! @rochacbruno

**Comment by rochacbruno** [comment]
Hi @AminHP this is not yet supported, I like the idea lets see how to implement it.

**Comment by rochacbruno** [comment]
Connected to #14

**Comment by AminHP** [comment]
This is a basic and easy algorithm.
We define a property with the following structure:
  import: "yamlfilepath"

Before process anything, we can find all the  import keywords, read contents of the file located in the yamlfilepath, and replace them with the import property.
After that the Flasgger can process everything like before and no action is required.

**Comment by rochacbruno** [comment]
@AminHP I can try to work on this in the next weeks but will take some time as I am going to travel for some days.

If you can implement, your Pull Request will be very welcome!

The `import` algorithm must be called at the end of this function https://github.com/rochacbruno/flasgger/blob/master/flasgger/base.py#L42-L54

(maybe recursively)

**Comment by AminHP** [comment]
Ok. I will implement it. Help me please if i had any problems. Thanks!

**Comment by AminHP** [comment]
Ok. I will implement it. Help me please if i had any problems. Thanks!

**Comment by AminHP** [comment]
Please check my pull request. @rochacbruno

**Comment by rochacbruno** [comment]
Merged thanks!
