### ISSUE TITLE
cannot access the website using my host ip

### ISSUE THREAD

**Issue by coolguy456** [rochacbruno/flasgger#54]
Hi , flasgger made my task easier in creating documentation for my api but I cannot access the documentation unless the flask-api is hosted on 5000 and also cannot access documentation on my IP(http://10.0.5.40:5000/apidocs/index.html)  but can access when localhost is used. Any suggestions?

**Comment by rochacbruno** [comment]
Hi

When starting your app you can pass the host and if want to access out of localhost you need to pass `0.0.0.0`

app.run(host='0.0.0.0', port=8080)

should work.

**Comment by coolguy456** [comment]
thanks it worked.
