### ISSUE TITLE
Getting empty results with example_app

### ISSUE THREAD

**Issue by chrischnweiss** [rochacbruno/flasgger#55]
Hi there,

using the example_app which is provided with this project, Im getting a empty result for the "paths" object of the specification. So the UI is empty for those routes.

Anyone else with this problem?

Cheers,
Christian

**Comment by rochacbruno** [comment]
@chrischnweiss I just did a major refactor

Please try again

Clone repo again (or update current)

` python examples/example_app.py`

**Comment by chrischnweiss** [comment]
Running into the next issue know:

`➜  flasgger git:(master) python examples/example_app.py
Traceback (most recent call last):
  File "examples/example_app.py", line 175, in <module>
    @swag.definition('Hack', tags=['v2_model'])
AttributeError: 'Swagger' object has no attribute 'definition'`

**Comment by rochacbruno** [comment]
@chrischnweiss you probably doesn't have the master version in your env.

```bash
pip uninstall flasgger
pip install https://github.com/rochacbruno/flasgger/tarball/master
```

**Comment by chrischnweiss** [comment]
That's it! I installed via pip package! 
Thank you!
