### ISSUE TITLE
Add Travis testing for examples

### ISSUE THREAD

**Issue by lwm** [rochacbruno/flasgger#64]
Would you be interested? I'd try to set it up, we could just figure out a way to fire up each examples Flask server and check that it runs and then kill it. This would give guarantees the examples are working.

**Comment by rochacbruno** [comment]
Hey @lwm that would be nice! I was thinking on using Flask client for testing and then testing only if output /specs and /apispecs_1 is valid swagger using a swagger validation tool.

**Comment by lwm** [comment]
Oh, that's an even cooler idea!
