### ISSUE TITLE
Add a change log?

### ISSUE THREAD

**Issue by lwm** [rochacbruno/flasgger#65]
http://keepachangelog.com/en/0.3.0/

Would be nice! I'll rely on this library for my project going forward and would like to keep an eye on the changes you'll be making here.

**Comment by rochacbruno** [comment]
@lwm nice! I'll add

**Comment by lwm** [comment]
Thank you! Very much appreciated :) Feel free to close.

**Comment by rochacbruno** [comment]
I'll wait the next release to PYPI to add this changelog, so I'll take care of adding all the history. 

By now keeping this one open.
