### ISSUE TITLE
How to fold Flasgger API listings

### ISSUE THREAD

**Issue by lwm** [rochacbruno/flasgger#66]
Would be cool to join the /api/auth/ GET/POST under the one /api/auth. 

I've seen this doable in django-rest-swagger libraries. Is it possible in flasgger?

![image](https://cloud.githubusercontent.com/assets/1991377/24407486/f49a878e-13c2-11e7-94d7-e0b320bdedce.png)

**Comment by rochacbruno** [comment]
@lwm I have to check. I know we can group by tags, so paths with the same tag goes under the same folding.

**Comment by lwm** [comment]
> I know we can group by tags

Ah yes, that was what I was looking for! Thanks!
