### ISSUE TITLE
Handling multiple http methods and routes for a single function.

### ISSUE THREAD

**Issue by GGross5213** [rochacbruno/flasgger#7]
How does flasgger handle multiple http methods in a single route? It seems that there is no way to have two different sets of documentation for view function that has a GET and POST. Also I have view functions that have multiple routes such as /events and events/:id. How can I produce two separate definition objects?

**Comment by rochacbruno** [comment]
It is possible to have different sets of docs, but it is handled by swagger not flasgger.

the http method have to be checked, did you testes it?

**Comment by rochacbruno** [comment]
I am working on making this available

```python

@swag_from('filename', methods=['POST'])
@swag_from('another_filename', endpoints=['test'])  # all methods
@swag_from('another_filename', endpoints=['another'], methods=['GET')
@route('/', endpoint='test')
@route('/<test>', endpoint='another')
def view():
    ...
```
