### ISSUE TITLE
[front end] Improve demo app html template

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/flasgger#81]
This is the current demo app http://flasgger.pythonanywhere.com/

we need to improve that template currently showing a simple ul/li list.

would like to have a responsive grid with each example in a block, something like: http://codepen.io/maddesigns/pen/KdoOmO

html template to change is https://github.com/rochacbruno/flasgger/blob/master/demo_app/templates/flasgger.html#L50-L64

To run the demo app locally:

```bash
$ git clone https://github.com/rochacbruno/flasgger/
$ cd flasgger/
# create or activate a virtualenv (optional)
$ pip install -r demo_app/requirements.txt
# you must be in flasgger root folder
$ python demo_app/app.py --debug --reloader 
```

visit http://localhost:5000

**Comment by ThiagoLopes** [comment]
Try this: 

1.  in line 50 add this class in ul  : `listFlex`
2. add [this ](https://codepen.io/anon/pen/xqMRPX.css)stylesheet in head 

Will look like this:
![screenshot at 2017-04-01 18-30-22](https://cloud.githubusercontent.com/assets/5994972/24582592/935b4e5a-1709-11e7-906d-76df48bf0a6a.png)
