### ISSUE TITLE
Compatibility with FlaskRestless

### ISSUE THREAD

**Issue by laranicolas** [rochacbruno/flasgger#86]
Hey, I tested flasgger with Flask alone and work pretty well, good work!

I'm working with a flask proyect and we are using `FlaskRestless` extension, how can I make it work with `preprocessors` using `swag_from` directive??

**Comment by rochacbruno** [comment]
Hi, I never used FlaskRestless, I need to check it out to see how it works.

Can you share a simple example of app using this?

**Comment by laranicolas** [comment]
Yes sure, 2 years ago I pushed this repo.

https://github.com/laranicolas/flaffold

**Comment by laranicolas** [comment]
@rochacbruno did you see something?

There is a way to pre-define endpoints using template? I tried with `paths` but didn't work...

**Comment by laranicolas** [comment]
@rochacbruno any update?

**Comment by laranicolas** [comment]
@rochacbruno I never received any response about this issue.

**Comment by rochacbruno** [comment]
Hey @laranicolas I had no time yet to play with Restless library, sorry, trying to get some more people to contribute with this.

**Comment by laranicolas** [comment]
Ok, I understand @rochacbruno, but there is a way to pre-define endpoints using template? (without  using decorators).

**Comment by rochacbruno** [comment]
@laranicolas yes!

Just pass a complete template

```python
Swagger(app, template={...})
```
or

```python
Swagger(app, template_file='file.json|yaml')
```

Examples:

https://github.com/rochacbruno/flasgger/blob/master/examples/colors_template.json
https://github.com/rochacbruno/flasgger/blob/master/examples/colors_template_json.py

**Comment by laranicolas** [comment]
Great, so I will use that way.

Thanks.
