### ISSUE TITLE
flask-restful - generating the swagger spec automatically?

### ISSUE THREAD

**Issue by lwm** [rochacbruno/flasgger#87]
In flask-restful, we use:
  1) [Argument parsing](https://flask-restful.readthedocs.io/en/0.3.5/quickstart.html#argument-parsing) to check the incoming request conforms to what we want.
  2) [Data formatting](https://flask-restful.readthedocs.io/en/0.3.5/quickstart.html#data-formatting) to assure the response is in the way we want it.

As far as I can see, the [flasgger X flask-restful](https://github.com/rochacbruno/flasgger#using-flask-restful-resources) integration requires that we still *manually* write the YAML specification of the schema? Is this correct? If so, what might be needed to get this working automatically.

And yes, I'd be happy to put in the work here :)

**Comment by lwm** [comment]
I suppose we could adapt the [marshmallow](https://github.com/rochacbruno/flasgger#using-marshmallow-schemas) generating code or?

**Comment by rochacbruno** [comment]
That would be nice if we can get the specs automatically, But as I am not a restful user I don't know too much about its internals.

If we can patch `Resource` class and use `Resource` and `Schema` imported from `flasgger` package then it may work.

It would be very nice if you can come with some experiments on this, thanks.

**Comment by lwm** [comment]
Hey, thanks for getting back to me. I did some investigation and it seems that the argument and data formatting modules in flask-restful are kinda limited and people are [already using marshmallow](https://github.com/flask-restful/flask-restful/issues/335). So, I'll close this off and stick with your marshmallow support.
