### ISSUE TITLE
How to configure different swagger URI?

### ISSUE THREAD

**Issue by lwm** [rochacbruno/flasgger#99]
I would like to use something else than `/apidocs/`, is it possible? I tried setting [specs_route](https://github.com/rochacbruno/flasgger/blob/master/flasgger/base.py#L346) in my configuration but it didn't work. Something I'm missing?

**Comment by rochacbruno** [comment]
specs_route must work, isn't it?
```python
app.config['SWAGGER'] = {
    ...
    'specs_route': '/other/',
    ...
}
```

**Comment by lwm** [comment]
Ah! It works. I was confused with the [initializing](https://github.com/rochacbruno/flasgger#initializing-flasgger-with-default-data) docs and the configuration. Thanks!
